version: '3.8'
services:
  api:
    image: ucwa
    build: .
    command: "npm start"
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
    restart: unless-stopped